name: Tag Version

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - '.github/workflows/publish.yml'

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get package version
        id: pkg
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - name: Check if tag exists
        id: check_tag
        run: |
          git fetch --tags
          if git tag | grep -q "^v${{ steps.pkg.outputs.version }}$"; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Create and push tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ steps.pkg.outputs.version }}
          git push origin v${{ steps.pkg.outputs.version }}
